#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

git fetch origin main --quiet && git rebase origin/main --quiet
echo "origin main rebased onto current branch"

yarn run lerna run --concurrency 1 --stream pre-push
